spring:
  sql:
    init:
      mode: always

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092

  application:
    name: testcontainerssamples

backbase:
  activemq:
    enabled: false